name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: JoanaPixel
          outputs: |
            ./github-contribution-grid-snake.svg
      - name: Push snake animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "github-contribution-grid-snake.svg"
